# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "./terraform.tfstate"
    resource_group_name  = "terragrunt-state-rg"
    storage_account_name = "tgstatedev"
  }
}
